name: 'Conventional Pull Requests'
description: 'Checks PR names against conventional commits using commitlint'
author: 'Andy Chubb'
inputs:
  configuration-path:
    description: 'The path for the commitlint config'
    required: false
    default: './commitlint.config.js'
runs:
  using: 'node16'
  main: 'dist/esm/main.js'
